create table "public"."category" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "created_at" timestamp with time zone default now()
);


alter table "public"."category" enable row level security;

create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "category" bigint,
    "price" integer,
    "created_at" timestamp with time zone default now()
);


alter table "public"."products" enable row level security;

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (id);

CREATE UNIQUE INDEX products_category_key ON public.products USING btree (category);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

alter table "public"."category" add constraint "category_pkey" PRIMARY KEY using index "category_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."products" add constraint "products_category_fkey" FOREIGN KEY (category) REFERENCES category(id) not valid;

alter table "public"."products" validate constraint "products_category_fkey";

alter table "public"."products" add constraint "products_category_key" UNIQUE using index "products_category_key";


